# MariaDB setting
server:
  port: 8080

spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
#MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3306/encore
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: maria

  # Hibernate config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # 서버열면 생성 닫으면 drop
    database-platform: org.hibernate.dialect.MariaDBDialect

  # View
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

  #thymeleaf auto refresh
  thymeleaf:
    cache: false

# TestTableMapper.xml 파일이 위치하는 경로
# **은 하위 폴더 레벨에 상관없이 모든 경로를 뜻하며, *는 아무 이름이나 와도 된다는것을 뜻한다.
# mybatis mapping
# mapper.xml  location
#mybatis:    #JPA할때는 주석처리 하자
#  type-aliases-package: com.example.demo.day2.mapper
#  mapper-locations: mybatis/**/*.xml

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: Hj2dzMLqv3leuzogGOlS
    secret: 5owUz4pjuz

